//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebFormSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public int OrderStatusID { get; set; }
        public string OrderStatusCode { get; set; }
        public string OrderStatusName { get; set; }
        public byte SortOrder { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
