//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebFormSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int PurchaseOrderID { get; set; }
        public int VendorID { get; set; }
        public Nullable<int> SubmittedByID { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<int> ApprovedByID { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string PaymentMethod { get; set; }
        public string Notes { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
