//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebFormSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Welcome
    {
        public int ID { get; set; }
        public string Welcome1 { get; set; }
        public string Learn { get; set; }
        public string DataMacro { get; set; }
    }
}
